name:

   on:
    puah:
       Braches:
       - master


    jobs:
       build:
         run-on: ubunbtu-latest
          steps:
            -name: checkout code
              uses: actions/checkout@v2
            -name: setup .NET 5
               uses: action/setup-donet@v1
                     dotnet-version: dotnet '5.0.x'


-name: Restore and Build Dependencies
  run: dotnet restore

  -name: Build App
    run: dotnet build -c release --no-restore
      
    
